[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = "*"
tokio = { version = "1.39.2", features = ["rt", "rt-multi-thread", "macros", "full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
futures = "0.3.30"
tokio-stream = "0.1.15"